version: '3.8'

services:
  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - supabase

  # Supabase Local Development
  supabase:
    image: supabase/postgres:15.1.0.53
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: quickbite
    volumes:
      - supabase_data:/var/lib/postgresql/data

  # Redis for Caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  supabase_data:
